### ISSUE TITLE
Recognition for IIDX controller premium model

### ISSUE THREAD

**Issue by staraxis1684** [exch-bms2/beatoraja#143]
I think beatoraja pretty good bms player. Thanks to this project very much.
Then, I found a problem of recognition for IIDX controller premium model (INFINITAS controller).
I play doubleplay mode, so I set up the configulation of controller to "2dx dp" and select those controller to each player side, however, when I quit the game and reboot it, the setting of 2P side has been initialized.(not saved?)

I'll appreciate you to fix this problem.

**Comment by parataxia** [comment]
So it works each time you play but you must re-configure the 2P side each time?

- Does the INFINITAS controller have independent game ports per controller? Or is it one game port for DP entirely? (you can check when pressing '6' in Select.. and adjusting the  "Controller device.") Try adjusting 1P side and 2P side to have independent ports. 

Also screen captures of the KeyConfig screen might prove useful.

Only other thing I can think of is perhaps making sure you press `Esc` when exiting Beatoraja. I've had issues with the game not saving config etc initially when having a fresh build to set up.

**Comment by staraxis1684** [comment]
Hi parataxis, and I appreciate you for your reply.
I'll show you my setting as bellows.

1. Correct setting
![beatoraja_correct](https://user-images.githubusercontent.com/34341717/34108253-ba420a34-e442-11e7-9986-1f8e77a924d6.png)

2, Incorrect
![beatoraja_incorrect](https://user-images.githubusercontent.com/34341717/34108304-e77f97e6-e442-11e7-872e-593c6777dcae.png)

Whenever I play beatoraja, I must set up this setting. Furthermore, When I quit the game by pressing ESC, this setting reset to incorrect setting.

**Comment by parataxia** [comment]
A few things to mention are the characters in "Controller Device" are obviously not being trans-coded to the proper character encoding I'm guessing. I looked at the code yet noticed the text data type of the controller is a String type, and this looks like SHIFT-JIS code page being decoded as UTF-8? A solution would be to convert to a non-unicode byte char array (String.getBytes method?) and feed it the proper codepage to convert to. 

I heard the controller works fine in LR2 persistently so hopefully this gets resolve'd soon for everyone.

**Comment by parataxia** [comment]
The only other possible scenario is for some bizarre reason you actually need UTF-8 enabled for beatoraja explicitly because config settings do not save properly at times. Ideally this would've been fixed in the beginning development of the game but can corrupt settings sometimes, so please beware.  Please follow these instructions by the tee and I am not responsible for your settings becoming malformed or otherwise destroyed! 

 **- Make a back up of `config.json` and also your `player` folder in the parent directory of beatoraja FIRST.** 
    - Open config.json and click `Save as`, then go ahead and save it to the same location (i.e C:\beatoraja\)
    - Do this to the the inner-most folder of `player`'s `config.json` as well.
    - Open the boot script of your choice (beatoraja-config/32.bat, etc) in notepad.
    - Add this to the very top of the script : 
        ```set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8``` then repeat the same step for saving in the `player` folder.

Try launching the game now and check all your settings. If you find settings to be off in certain ways, look at your backup folder to apply them accurately again. Hope this helps.
