### ISSUE TITLE
Left scratch lane "sticks" in DP

### ISSUE THREAD

**Issue by Tearff** [exch-bms2/beatoraja#286]
In 14key, hitting left and right scratch at the *exact* same moment causes left scratch to never release. The laser stays lit, and I need to press that scratch again to unstick it. If I don't unstick it, the next scratch note on that lane will be a miss.

Keys pressed are L-shift and R-shift.
![20180413_130827_config](https://user-images.githubusercontent.com/6359267/38733982-de2d3a02-3f1b-11e8-8d31-61fb70f56513.png)

beatoraja 0.5.5

**Comment by Tearff** [comment]
I did some testing. This problem happens when lshift and rshift are *released* at the same moment. They don't have to be pressed at the same time.

**Comment by wcko87** [comment]
This happens in SP too.
If you release F-SCR and R-SCR at the same time, the note beam will not disappear.

**Comment by wcko87** [comment]
I investigated this issue.
This issue seems to be a problem with LibGDX. It only happens with LSHIFT and RSHIFT.

If you release LSHIFT and RSHIFT at the same time, LibGDX cannot detect it.
It will only detect RSHIFT's release. It will continue to think LSHIFT is being held down.
The issue will only go away if LSHIFT or RSHIFT is pressed again.

It is easy to test by checking `isKeyPressed(59)` and `isKeyPressed(60)` with the following code:
VIDEO: https://gfycat.com/ApprehensiveAccurateAfricanhornbill
```java
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.ApplicationListener;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;

public class Test {
    public static void main(String[] args) {
        new LwjglApplication(new ShiftKeyTester());
    }
}

class ShiftKeyTester implements ApplicationListener {
    @Override
    public void create() {        
    }

    @Override
    public void dispose() {
    }

    @Override
    public void render() {       
        System.out.println(Gdx.input.isKeyPressed(59) + " <L | R> " + Gdx.input.isKeyPressed(60));
    }

    @Override
    public void resize(int width, int height) {
    }

    @Override
    public void pause() {
    }

    @Override
    public void resume() {
    }
}
```

I tried using LibGDX's `InputProcessor` (`keyUp` and `keyDown`) too. It has the same problem.
So I think this problem cannot be fixed unless LibGDX fixes the bug.
(I think it also may not be a LibGDX bug. It may be a bug with LWJGL)

But I think this is a serious issue for 1P or DP players, because this bug can cause players to miss scratch notes if they use LSHIFT for the main scratch key.
