### ISSUE TITLE
Scroll doesn't fall when select some music in a row. And beatoraja doesn't remember some settings

### ISSUE THREAD

**Issue by mhsneve** [exch-bms2/beatoraja#318]
Version: beatoraja 0.5.5
Java version: 8.0.1710.11(64 bit)

Scroll doesn't fall when select 点、線、面、立点 in a row. But it normally works when selected sparsely. And it normally works in LR2 when selected in a row.
BMS Path: C:\Program Files (x86)\LR2beta3\Insane Bms\点、線、面、立体

And beatoraja doesn't remember some settings like note, lanecover, framecover, lane brightness and then some. 
Skin: LITONE5 0.8.5

Thanks for reading.

**Comment by exch-bms2** [comment]
Sorry. I can't understand the situation you wrote. Can you tell us the details?

**Comment by mhsneve** [comment]
When I select 点、線、面、立点(★1) and reselect it right after, beatoraja is shut down. (I thought scroll doesn't fall, but it's my mistake.) But when I reselect it after selecting another music, it works normally.

And some settings are initiallized when beatoraja is restarted. 

I sent some videos and image to your mail address to help understanding the situation. I can't attatch it here because of its size. 

Thanks for reading and sorry for your confusion.

**Comment by wcko87** [comment]
I believe these are locale issues.

If you select a song with japanese (or other strange characters) in the video/audio path (either the folder name or the name of the video/audio files), the resources will fail to load the first time, and beatoraja will crash the second time you load the song.

Regarding the settings not saving, this happens when the setting names have japanese/other characters in them. These special characters are saved to the .config files as ????, which makes beatoraja unable to recognize them the next time they start up.
Suggestion: convert japanese characters to UTF-8 before saving the .config files? (so that they work correctly even if in a non-japanese locale)
