### ISSUE TITLE
Duplicate class files

### ISSUE THREAD

**Issue by RoanH** [exch-bms2/beatoraja#32]
I discoverd something odd about the beatoraja jar.
If you open the jar and go to the package: `com.fasterxml.jackson` and all subpackages you'll notice that every class file occurs twice. 
[Image of the directory listing](http://i.imgur.com/LyPZrcn.png)
I guess it's not a huge problem, but I am surprised that it's possible to create a jar with files with the same name in the same directory. It also makes the jar bigger.

The issue probably comes from two dependencies with the same classes. `jbmstable-parser.jar` and `jbms-parser.jar` maybe?

**Comment by parataxis** [comment]
OK - I've tried multiple potential solutions and still no go... not good because there are many duplicates included in the jar file besides the 'jbmstable*.jar' files I think... If you have it working in Eclipse, there is a nice tool ("Classpath Checker Eclipse") that comes as a plugin, but alas, will not work when trying to import from github's repos because it won't let me create a New Java Project for some reason. So if your build environment is using Eclipse, please try using that tool mentioned above and let me know of feedback.

btw: looks like the 0.4 release binary build is also similarly large, if not identically large... this is a strange issue. 

Thanks!

**Comment by RoanH** [comment]
Glad you were to resolve this :)
Since this was fixed in pull request: https://github.com/exch-bms2/beatoraja/pull/33
I'm closing this issue.

**Comment by RoanH** [comment]
Reopening since it's apparently not fixed entirely, see: https://github.com/exch-bms2/beatoraja/pull/34
