### ISSUE TITLE
Rich Presence support

### ISSUE THREAD

**Issue by marysiamzawka** [exch-bms2/beatoraja#357]
Something as simple as showing the artist, title and difficulty of the chart currently played by you would be nice

**Comment by FenekAlfa** [comment]
Yet another shill looking to latch their overlord onto someone else's work for ad money.

I used to use Dolphin and Citra. Both of them added this, which allegedly should do nothing since I never had(nor ever want to) used, installed or interacted in any way with Discord. However, I keep my adblocker off on three sites I want to support, and after a few days I noticed the ads suddenly going from zero to almost all of them being gaming related. My complaints about it have mysteriously disappeared(and I'm screenshotting this one in case it does too, although they weren't on GitHub). 

I have since set my adblocker to work everywhere. I have also bought a Wii, and am looking to buy a 2DS/3DS too. If beatoraja devs make the mistake of adding RPC, it'll be back to Wine-ing LR2 or ruvit(I've done both at some point) for me.

As for you and your workmates/friends/strangers with same goal/whatever is the relation or lack of it of you and other people shilling(not that I care), something as simple as staying the fuck out of free software would be nice.

**Comment by skielred** [comment]
@FenekAlfa  Discord RPC uses Inter-Process Communication which means it never leaves your computer.
It simply tells your own machine information that the Discord client can read. So you will be sending those informations to Discord only if you actually have Discord running on your computer.
Basically beatoraja would be sharing information in an open way to your computer, if Discord is open on your computer it will read this information and update your status accordingly.

Believing your private information was shared because of Discord RPC being implemented is a big misunderstanding of how IPC works and I suggest that you read the Wikipedia article https://en.wikipedia.org/wiki/Inter-process_communication.

I do believe beatoraja and the BMS community can benefit from Discord RPC support, showing your friend what songs you are playing can sometime raise interest in the game and BMS itself.
I recommend having a look at https://github.com/MinnDevelopment/java-discord-rpc
