### ISSUE TITLE
Changing scroll speed also lowers/raises the lanecover

### ISSUE THREAD

**Issue by UserZ1** [exch-bms2/beatoraja#398]
If i try to adjust the scroll speed while lanecover is enabled the lane cover also lowers/rises.

**Comment by potchy** [comment]
I'm sure that's intended, as that's what IIDX does originally. It would be nice to have an alternative though.

**Comment by wcko87** [comment]
If you hold START (default Q) and rotate the turntable, what is happening is that you're adjusting the lanecover, not the scroll speed. The scroll speed is automatically adjusted so that the green number remains constant.

If you want to adjust the scroll speed itself, adjust the green number by holding SELECT (default W) and rotating the turntable instead.

I think this issue can be closed...?
