### ISSUE TITLE
Questions about course and manual.

### ISSUE THREAD

**Issue by RIVERSTAR2190** [exch-bms2/beatoraja#413]
*Can I delete my own created courses?

In 'course'tab, when I making some dp courses and satellites, I accidently added wrong course, but I can't finid 'delete' button..

*Can I import my courses into level table?

As I know, betoraja doesn't have 'course import' feature,(like .lr2cs files)
so I made my own class courses. (insane dp and satellite)
Can I import these into their level tables like 第2発狂難易度 and 第2通常難易度?
(In beatoraja default leveltable setting,  第2発狂難易度 and 第2通常難易度 has their own class(course))

*Where can I find beatoraja manual?
In this site (http://desout2.freeiz.com/beatoraja-0.6.7.html)
beatoraja have new GAS settings but I can't find how to use this.
If beatoraja has some manual guide, could you tell me where it is?

Thanks for your hard work.

**Comment by wcko87** [comment]
Insane2 table is managed by its creator, only the creator of the table can edit it. If you want to make your own courses or tables, you should make a separate table.
Also, satellite will be receiving its official dan courses soon.

I think it would be better to ask questions in the appropriate discords, instead of creating issues.
[bms server japan](https://discord.gg/DvxHfEa) or [bms international](https://discordapp.com/invite/0lUN07Rj1O8Sdctv)

**Comment by Shimi9999** [comment]
> beatoraja have new GAS settings but I can't find how to use this.

It's the Bottom Shiftable Gauge on Play Option tab.
![20190131_bsg](https://user-images.githubusercontent.com/38182044/51991769-25b65200-24ef-11e9-9ed7-4ea6afeaf2e4.png)

Spesification #394 (japanese).
