### ISSUE TITLE
[Linux] No sound in some BMS

### ISSUE THREAD

**Issue by skielred** [exch-bms2/beatoraja#477]
I've just setup beatoraja on Linux, when trying to play BMS from BMS StarterPackage 2018, every BMS I tried to launch that use ogg keysounds did not make any sound, while the ones that use the WAV files worked normally.

This is especially weird because the soundset I use in my skin use ogg but work correctly.

Here are the ffprobe output for different files:

<details>
<summary>An ogg file in my soundset skin that plays correctly</summary>

```
Input #0, ogg, from 'skin/isocosa_brook/brook_sound_fx/f-open.ogg':
  Duration: 00:00:00.40, start: 0.000000, bitrate: 262 kb/s
    Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp, 192 kb/s
```
</details>
<details>
<summary>An ogg file from any BMS from StarterPackage 2018 that does not play at all</summary>

```
Input #0, ogg, from 'Local Songs/GENOSIDE -Starter Package 2018-/[nora2r]bbkkbkk/02.ogg':
  Duration: 00:00:00.35, start: 0.000000, bitrate: 253 kb/s
    Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp, 192 kb/s
```
</details>
<details>
<summary>A wav file from any BMS from StarterPackage 2018 that plays correctly</summary>

```
Input #0, wav, from 'Local Songs/GENOSIDE -Starter Package 2018-/[Lime]renai_syndrome/Musicbox01_000.wav':
  Duration: 00:00:00.71, bitrate: 1411 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
```
</details>

I've tried both running beatoraja from source at revision https://github.com/exch-bms2/beatoraja/commit/8763e792b729d951e35e000b33277844a82d8dc9 and the compiled build for 0.7.3 from the mocha-repository.info page.

I use Fedora, ~~I use OpenJDK~~ I tried with **both** OpenJDK and Oracle's JRE and have installed `javafx` to run/compile beatoraja.

Oracle's JRE version:
```
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
```
OpenJDK version:
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

**Comment by exch-bms2** [comment]
It doesn't happen on my environment (Ubuntu 18.04, JRE1.8.0_221. test BMS : B.B.K.K.B.K.K Another).

The defference between GitHub 0.7.3 and Mocha 0.7.3 is libGDX version (nightly-20171213 -> 20190913), JavaCV version (1.3.3 -> 1.5.0, Mocha 0.7.2 uses 1.5.1 but this version has a problem), and MochaIRConnector plugin.
If this happens only on Mocha version, maybe caused by libGDX version : beatoraja uses OpenAL and ogg decoder in libGDX.
What do you think?

**Comment by skielred** [comment]
Sadly, as I said in my post, this happen in both Mocha and GitHub version. I'm clueless as to where to investigate for this issue :(

**Comment by exch-bms2** [comment]
Maybe caused by beatoraja Audio Processing.

beatoraja processes skin sounds and key sounds on bms.player.beatoraja.audio.GdxSoundDriver (extends AbstractAudioDriver, when using OpenAL).
Processing skin sound is slightly different from key sounds : 

- AbstractAudioDriver.play(Note n, float volume, int pitch) : play key sound defined on Note
- AbstractAudioDriver.play(String p, float volume, boolean loop) : play skin/preview sound (String - file path)
- AbstractAudioDriver.setModel(BMSModel model) : load all key sound on BMS and prepare.

Please see these methods to solve this problem.

**Comment by skielred** [comment]
I've tried debugging the issue and found out that on songs that do not work, this check at https://github.com/exch-bms2/beatoraja/blob/master/src/bms/player/beatoraja/audio/AbstractAudioDriver.java#L352 fails (`wav` is null)
![image](https://user-images.githubusercontent.com/9400466/66150451-81545480-e615-11e9-8c8b-1356473a1190.png)

`id` isn't really weird, I get values between 0 and 300~ depending of where I am in the song.

By investigating further I found that `wavmap` is filled with null, as I could fall into this conditional at https://github.com/exch-bms2/beatoraja/blob/master/src/bms/player/beatoraja/audio/AbstractAudioDriver.java#L260!!
![image](https://user-images.githubusercontent.com/9400466/66150920-806ff280-e616-11e9-81b6-97b0738649ff.png)

The content of `wavmap` reports nulls but has a normal size (~500 per song). Maybe it's a problem with `cache`?

**Comment by exch-bms2** [comment]
Now I pushed the fixed code about this issue. Please check working collectly on your environment.

**Comment by skielred** [comment]
Thank you, the fix introduced in https://github.com/exch-bms2/beatoraja/commit/9b9107dce659e41441d932be6d10aaeb79fd375b fixed it :tada:

I hope I was at least of some help

I'm closing the issue
