### ISSUE TITLE
From 0.7.3 onwards, Bitmap fonts don't work on song bars in json/lua skins

### ISSUE THREAD

**Issue by wcko87** [exch-bms2/beatoraja#483]
This bug is a regression from beatoraja release 0.7.3+
Bitmap fonts on the song select wheel worked correctly on 0.7.2 and below.

## How to reproduce:
Use a skin that has a bitmap font for the song titles on the song select wheel.
The skin must be either in .json or .lua format.
(Currently only the LITONE6 skin has this)

**Comment by doneara** [comment]
この問題は以下の部分を以前のコードに変更すれば解決します。
https://github.com/exch-bms2/beatoraja/commit/b5825e0179443a80510a24e8e85d049a2552ff03

このBitmap fontsで一番問題なのは画像をメモリに格納してると思うのですが
次の画面に移行してもメモリ内の画像が破棄されず溜まり続けるので
メモリ使用量が最大になりソフトが落ちます。

**Comment by shellqiqi** [comment]
I find that the font bitmaps are not loaded because the `load` function is not called. Furthermore, it is not recommended to assign the member `font` several times like the code before #466.

So i submit a pull request #489 to fix this problem.

A patched jar branched from 0.7.4 will be found my forked repo [here](https://github.com/shellqiqi/beatoraja/releases/tag/0.7.4).

**Comment by doneara** [comment]
Thank you so much for fixing!
