### ISSUE TITLE
GPL Violation

### ISSUE THREAD

**Issue by adenosie** [exch-bms2/beatoraja#511]
The GPL License states that when you distribute the program, you must provide the full source code with the binary, or write down a notice so that anyone with only the binary file can get the source code.
However, there is no such notice in the zip file from the link at release tab.

**Comment by SackMagiclight** [comment]
(Opinion & Expectation)

The author himself is not tied to the license.
https://www.gnu.org/licenses/gpl-faq.en.html#ReleaseUnderGPLAndNF

However, because it is open source, it may be a violation if contributors may not agree with the author's binary distribution (including closed source).

Since IR-related functions that require security have been modified so that they can be separated, we expect that the author's proprietary code will also be separated into separate binaries.
