### ISSUE TITLE
Sending mail aborted in mocha-repository.info

### ISSUE THREAD

**Issue by vus7294** [exch-bms2/beatoraja#590]
It Seems Fixed server, But I CAN'T STILL RESET MY PASSWORD Because Keeps Pop out with Sending mail aborted Error Message.
MY Email Address is vus7294@gmail.com .

**Comment by exch-bms2** [comment]
You seem to be banned due to sending illegal BMS files:
https://mocha-repository.info/song.php?sha256=c4f49290fdbec6be2dd7cf88134e8958566d5d022b0dd4bbc2e1ab096c28d904
https://mocha-repository.info/song.php?sha256=d9e208aa36377e5d65b147b4ee5b928873d85cb9805fb85d14eed905093e648e
https://mocha-repository.info/song.php?sha256=d324291cb407a5cf1d2cdff6756bb8bbbdd3f5c5e256824611abf2e45e9b262e
These are 2DX-converted BMSes.

Banned user can't reset password (shows "Sending mail aborted" message).

I said "Don't use this application for playing illegal BMS files" (written on download page).

Thank you for debugging.
