### ISSUE TITLE
how can i use separate skin folder?

### ISSUE THREAD

**Issue by N-ISOGE** [exch-bms2/beatoraja#65]
i try to make a skin that does not depend on default.
but it's path seem like constant
Where do I change the contents of the configuration file?

**Comment by exch-bms2** [comment]
You can edit copies of default json skin file (ex. play7-isoge.json), and select this on Skin tab.

**Comment by Agrrox** [comment]
Is there some documentation for making theme for beatoraja?

**Comment by N-ISOGE** [comment]
i make the copy from default , change folder and skin name in the json file, and delete default skin folder but cmd window print "can't find skin₩default₩'something'

**Comment by LNTakeshi** [comment]
You can use edited files if you don't delete the default folder.
The default skin folder is indispensable to start beatoraja.
![2017-07-28 19 01 35](https://user-images.githubusercontent.com/4867425/28712817-86146aae-73c7-11e7-9858-e9a1f0e59f44.png)
![2017-07-28 19 01 56](https://user-images.githubusercontent.com/4867425/28712818-87883690-73c7-11e7-8a6f-5473f721aa7a.png)

Although there is no documentation, since it is similar to the specification of the LR2 skin, I think that it can be made with reference to it.
The added numerical values are listed in the following file and you can check the rough meaning.
https://github.com/exch-bms2/beatoraja/blob/master/src/bms/player/beatoraja/skin/SkinProperty.java
